[package]
name = "crypto"
version = "0.1.0"
authors = ["hermitsage <dth.bht@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pvss = { git = "https://github.com/zhtluo/rust-pvss" }
evss = { git = "https://github.com/zhtluo/rust-evss", branch = "main" }
rand = "0.7.3"
sha2 = "0.9.2"
serde = "1.0.118"
bincode = "1"
ark-serialize = { version = "0.2", default-features = false }
ark-ff = { version = "0.2", default-features = false }
ark-ec = { version = "0.2", default-features = false }
ark-poly = { version = "0.2", default-features = false }
ark-poly-commit = { version = "0.2", default-features = false }

ark-std = { version = "0.2", default-features = false }
ark-bls12-381 = { version = "0.2", default-features = false, features = [ "curve" ] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_pvss"
harness = false

[[bench]]
name = "bench_evss"
harness = false

[[bench]]
name = "bench_bi"
harness = false
